Feature/josecaste tasks sprint one
ViktoriyaRyazhska/Gdl-01.Java pull request #5
Opened 2022-09-24 16:54 UTC by JoseCaste

Task 4 and 9

2022-09-26 13:51 UTC, cesar-martinezg requested changes
Jose, overall it looks good, I added some comments that need to be addressed before approving/merging the PR.

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/MainApplication.java
> +            System.err.println("You has typed a wrong number.");
typo: "You have" instead of "You has"

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/MainApplication.java
> +            System.err.println("You must type a number from list.");
typo: "from THE list"

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/MainApplication.java
> +        taskListPath = System.getProperty(USER_DIR).concat("\\").concat("task-list.txt");
Some suggestions:

- use an static variable for the name of the file (task-list.txt)
- use an external property file for hosting the name of the file to be used.

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/MainApplication.java
> +                break;
add the "default" case, for those numbers/tasks that haven not been added

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/MainApplication.java
> +public class MainApplication {
Add documentation for the Main Class (purpose / high level description)

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/jose/TaskJoseSprintOne.java
> +     * Task 4 process
Task 9, isn't?

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/jose/TaskJoseSprintOne.java
> +     * Task 4 process
Add description of the task to the documentation: what is the purpose of the method, what will be calculated, etc.

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/jose/TaskJoseSprintOne.java
> +     * Task 4 process
Add more info regarding what this method is doing (input, output, calculation, high-level description of its objective)

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/jose/TaskJoseSprintOne.java
> +                System.out.println(" It's fit an exact number of pixels on the wall");
typo: "It fits an exact..."

2022-09-26 13:51 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/jose/TaskJoseSprintOne.java
> +                System.out.println(" Is not fit an exact number of pixels on the wall");
Typo: "It does not fit an exact..."

2022-09-27 02:19 UTC, JoseCaste commented on src/main/java/com/softserve/sprintone/jose/TaskJoseSprintOne.java
> +     * Task 4 process
Task 9 already is in line 53 and 63

2022-09-27 15:03 UTC, cesar-martinezg requested changes

2022-09-27 15:03 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/MainApplication.java
> +                System.out.println("Any number has matched");
Typo, better to use "The specified task has not been implemented".

2022-09-27 15:03 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/jose/TaskJoseSprintOne.java
> +     * task9 will prompt to the user values that is required for make a negative number.
typo "...for making a number negative"

2022-09-27 15:03 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/jose/TaskJoseSprintOne.java
> +    public static void task4(final BufferedReader bufferedReader) throws TaskException {
please avoid using static methods. Use regular methods and instantiate object from main class and call its inner methods.

2022-09-27 15:03 UTC, cesar-martinezg commented on src/main/java/com/softserve/sprintone/jose/TaskJoseSprintOne.java
> +                System.out.println("It does not fits an exact number of pixels on the wall");
Typo: "It does not fit"

2022-09-27 15:04 UTC, cesar-martinezg approved these changes
Thanks LGTM

2022-09-27 15:04 UTC, merged